# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
warnings_are_errors: false

before_install:
  - sudo apt-get install -y libproj-dev libgeos-dev libnetcdf-dev gdal-bin libgdal-dev  libgeos-dev

r_binary_packages:
  - reticulate
  - magrittr
  - data.table
  - sf
  - ggplot2
  - foreach
  - ggspatial

after_success:
  - Rscript -e 'devtools::install();devtools::test()'
  - Rscript -e 'library(covr); codecov()'


